# Generated by Django 4.2.6 on 2023-10-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Character Name')),
                ('level', models.IntegerField(default=1, verbose_name='Level')),
                ('experience_points', models.IntegerField(default=0, verbose_name='Experience Points')),
                ('character_class', models.CharField(max_length=20, verbose_name='Class')),
                ('background', models.TextField(blank=True, null=True, verbose_name='Background')),
                ('race', models.CharField(choices=[('Dragonborn', 'Dragonborn'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Gnome', 'Gnome'), ('Half Elf', 'Half Elf'), ('Half Orc', 'Half Orc'), ('Halfling', 'Halfling'), ('Human', 'Human'), ('Tiefling', 'Tiefling')], max_length=30, verbose_name='Race')),
                ('alignment', models.CharField(max_length=70, verbose_name='Alignment')),
                ('player_name', models.CharField(max_length=50, verbose_name="Player's name")),
            ],
        ),
        migrations.AddConstraint(
            model_name='character',
            constraint=models.UniqueConstraint(fields=('name', 'player_name', 'character_class', 'race'), name='name of constraint'),
        ),
    ]
