# Generated by Django 4.2.6 on 2023-10-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(max_length=50, verbose_name='Alignment'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.CharField(max_length=50, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Experience Points'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_name',
            field=models.CharField(max_length=50, verbose_name='Players Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Dragonborn', 'Dragonborn'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Gnome', 'Gnome'), ('Half Elf', 'Half Elf'), ('Half Orc', 'Half Orc'), ('Halfling', 'Halfling'), ('Human', 'Human'), ('Tiefling', 'Tiefling')], max_length=20, verbose_name='Race'),
        ),
    ]
