# Generated by Django 4.2.6 on 2023-10-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_alter_character_alignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Level'),
        ),
    ]
