# Generated by Django 4.2.6 on 2023-10-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
